# Generated by Django 5.0.2 on 2024-03-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.AddField(
            model_name='booking',
            name='desc',
            field=models.TextField(default='best event in brooklyn', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='tempName', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('entertainment', 'entertainment'), ('education', 'education')], default='education', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
