# Generated by Django 5.0.2 on 2024-03-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_booking_event_booking_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
