# Generated by Django 5.0.2 on 2024-03-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_booking_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
    ]
