# Generated by Django 4.2.7 on 2024-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fac_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('is_principle', models.BooleanField()),
                ('is_hod', models.BooleanField()),
                ('is_mentor', models.BooleanField()),
                ('is_dean', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ac_year', models.IntegerField()),
            ],
        ),
    ]
